greeting:
  message: "hello"
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: 123
    jdbc:
      url: jdbc:postgresql://localhost:5432/domanivendas

  # 2. Hibernate (Panache) Settings
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: import.sql